# Generated by Django 6.0.5 on 2026-05-31 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
