# Generated by Django 6.0.5 on 2026-05-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Project Number'),
        ),
    ]
