# Generated by Django 6.0.6 on 2026-06-04 13:46

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.project_image_upload_to),
        ),
    ]
