# Generated by Django 6.0.6 on 2026-06-04 13:46

import projects.models
import projects.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=projects.utils.ProjectFileSystemStorage(fallback='D:\\ai_projects\\CRM_main\\CRM\\media'), upload_to=projects.models.project_image_upload_to),
        ),
    ]
