# Generated by Django 6.0.5 on 2026-06-05 11:43

import projects.models
import projects.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=projects.utils.ProjectFileSystemStorage(), upload_to=projects.models.project_image_upload_to),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=projects.utils.ProjectFileSystemStorage(), upload_to=projects.models.project_image_upload_to),
        ),
    ]
