# Generated by Django 6.0.6 on 2026-06-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_budget_alter_project_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Project Number'),
        ),
    ]
