# Generated by Django 6.0.6 on 2026-06-15 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activity_action_alter_activity_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cloud', 'Cloud'), ('local', 'Local'), ('aggregator', 'Aggregator')], max_length=20)),
                ('api_key_enc', models.TextField(blank=True, db_column='api_key_enc', null=True)),
                ('base_url', models.CharField(blank=True, max_length=500, null=True)),
                ('selected_model', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('key_verified_at', models.DateTimeField(blank=True, null=True)),
                ('models_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('is_custom', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'indexes': [models.Index(fields=['provider'], name='core_aimode_provide_a62d4c_idx')],
                'unique_together': {('provider', 'model_id')},
            },
        ),
    ]
