# Generated by Django 6.0.5 on 2026-06-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('m', 'Meters'), ('m2', 'Square Meters'), ('m3', 'Cubic Meters'), ('l', 'Liters'), ('set', 'Sets')], default='pcs', max_length=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Common Material',
                'verbose_name_plural': 'Common Materials',
                'ordering': ['name'],
            },
        ),
    ]
