# Generated by Django 6.0.5 on 2026-06-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_category_delete_commonmaterial_material_category'),
        ('projects', '0003_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.project'),
        ),
    ]
