# Generated by Django 6.0.6 on 2026-06-16 06:10

import django.db.models.deletion
import materials.models
import projects.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_material_created_by_alter_material_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Material Number'),
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=projects.utils.ProjectFileSystemStorage(), upload_to=materials.models.material_file_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='materials.material')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
