# Generated by Django 6.0.5 on 2026-06-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='parts/'),
        ),
    ]
