# Generated by Django 6.0.6 on 2026-06-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_part_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
