# Generated by Django 6.0.6 on 2026-06-04 13:46

import parts.models
import projects.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='file',
            field=models.FileField(blank=True, null=True, storage=projects.utils.ProjectFileSystemStorage(), upload_to=parts.models.part_upload_to),
        ),
    ]
