# Generated by Django 6.0.5 on 2026-06-02 04:21

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file', models.FileField(storage=documents.models.DocumentStorage(), upload_to=documents.models.document_upload_to)),
                ('file_type', models.CharField(choices=[('contracts', 'Contracts'), ('reports', 'Reports'), ('drawings', 'Drawings'), ('photos', 'Photos'), ('invoices', 'Invoices'), ('other', 'Other')], default='other', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
