# Generated by Django 6.0.6 on 2026-06-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0006_alter_project_image_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('drawings', 'Drawings'), ('models_3d', 'Models 3D'), ('documents', 'Documents'), ('photos', 'Photos'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.project'),
        ),
    ]
