# Generated by Django 6.0.6 on 2026-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('drawings', 'Drawings'), ('models_3d', 'Models 3D'), ('documents', 'Documents'), ('photos', 'Photos'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
