# Generated by Django 6.0.6 on 2026-06-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_file_type_alter_document_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
    ]
