# Generated by Django 6.0.6 on 2026-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('document', 'Document'), ('pdf_catalog', 'PDF Catalog')], db_index=True, default='document', max_length=20),
        ),
    ]
