# Generated by Django 6.0.6 on 2026-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
